apiVersion: harness.io/v1
kind: component
name: first-component
identifier: firstcomponent
type: service
owner: group:account/_account_all_users
projectIdentifier: TEST
orgIdentifier: default
spec:
  lifecycle: development
  sourceCode:
    provider: Github
    repoName: UpSklling
    connectorRef: account.newconnector
    branch: main
    monoRepo: false
metadata:
  tags: []
  description: ""
