apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: sample-node-app-v1
  description: Sample Node.js application

spec:
  type: service
  lifecycle: development
  owner: _account_all_users